
/**************************************************************
 *	
 *	blam, 8 bit, 11025Hz,
 *	1 channel, 2535 bytes/channel
 *	Total Size: 1 * 2535 + 4 (header) = 2579 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\blam.aiff
 *	Time-stamp: Wed Nov 30 16:40:35 2016
 *	
 **************************************************************/

#ifndef __BLAMH__
#define __BLAMH__

#define BLAMFREQ 11025
#define BLAMLEN 2535

extern const unsigned char blam[2535];

#endif /* __BLAMH__ */
