
/**************************************************************
 *	
 *	bling, 8 bit, 11025Hz,
 *	1 channel, 3929 bytes/channel
 *	Total Size: 1 * 3929 + 4 (header) = 3973 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\bling.aiff
 *	Time-stamp: Mon Dec 05 17:55:12 2016
 *	
 **************************************************************/

#ifndef __BLINGH__
#define __BLINGH__

#define BLINGFREQ 11025
#define BLINGLEN 3929

extern const unsigned char bling[3929];

#endif /* __BLINGH__ */
