
/**************************************************************
 *	
 *	boom, 8 bit, 11025Hz,
 *	1 channel, 2801 bytes/channel
 *	Total Size: 1 * 2801 + 4 (header) = 2845 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\boom.aiff
 *	Time-stamp: Wed Nov 30 16:30:07 2016
 *	
 **************************************************************/

#ifndef __BOOMH__
#define __BOOMH__

#define BOOMFREQ 11025
#define BOOMLEN 2801

extern const unsigned char boom[2801];

#endif /* __BOOMH__ */
