
/**************************************************************
 *	
 *	crash, 8 bit, 11025Hz,
 *	1 channel, 9915 bytes/channel
 *	Total Size: 1 * 9915 + 4 (header) = 9959 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\crash.aiff
 *	Time-stamp: Sat Dec 10 13:34:11 2016
 *	
 **************************************************************/

#ifndef __CRASHH__
#define __CRASHH__

#define CRASHFREQ 11025
#define CRASHLEN 9915

extern const unsigned char crash[9915];

#endif /* __CRASHH__ */
