
/**************************************************************
 *	
 *	ded, 8 bit, 11025Hz,
 *	1 channel, 8847 bytes/channel
 *	Total Size: 1 * 8847 + 4 (header) = 8891 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\ded.aiff
 *	Time-stamp: Sat Dec 10 13:40:52 2016
 *	
 **************************************************************/

#ifndef __DEDH__
#define __DEDH__

#define DEDFREQ 11025
#define DEDLEN 8847

extern const unsigned char ded[8847];

#endif /* __DEDH__ */
