
/**************************************************************
 *	
 *	drum1, 8 bit, 11025Hz,
 *	1 channel, 88340 bytes/channel
 *	Total Size: 1 * 88340 + 4 (header) = 88384 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\drum1.aiff
 *	Time-stamp: Wed Nov 30 09:30:46 2016
 *	
 **************************************************************/

#ifndef __DRUM1H__
#define __DRUM1H__

#define DRUM1FREQ 11025
#define DRUM1LEN 88340

extern const unsigned char drum1[88340];

#endif /* __DRUM1H__ */
