
/**************************************************************
 *	
 *	drum2, 8 bit, 11025Hz,
 *	1 channel, 44360 bytes/channel
 *	Total Size: 1 * 44360 + 4 (header) = 44404 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\drum2.aiff
 *	Time-stamp: Tue Nov 29 16:34:45 2016
 *	
 **************************************************************/

#ifndef __DRUM2H__
#define __DRUM2H__

#define DRUM2FREQ 11025
#define DRUM2LEN 44360

extern const unsigned char drum2[44360];

#endif /* __DRUM2H__ */
