
/**************************************************************
 *	
 *	pom, 8 bit, 11025Hz,
 *	1 channel, 3411 bytes/channel
 *	Total Size: 1 * 3411 + 4 (header) = 3455 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\pom.aiff
 *	Time-stamp: Wed Dec 07 19:24:38 2016
 *	
 **************************************************************/

#ifndef __POMH__
#define __POMH__

#define POMFREQ 11025
#define POMLEN 3411

extern const unsigned char pom[3411];

#endif /* __POMH__ */
