
/**************************************************************
 *	
 *	winMusic1, 8 bit, 11025Hz,
 *	1 channel, 80553 bytes/channel
 *	Total Size: 1 * 80553 + 4 (header) = 80597 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\winMusic1.aiff
 *	Time-stamp: Sat Dec 10 14:30:12 2016
 *	
 **************************************************************/

#ifndef __WINMUSIC1H__
#define __WINMUSIC1H__

#define WINMUSIC1FREQ 11025
#define WINMUSIC1LEN 80553

extern const unsigned char winMusic1[80553];

#endif /* __WINMUSIC1H__ */
