
/**************************************************************
 *	
 *	winMusic2, 8 bit, 11025Hz,
 *	1 channel, 33539 bytes/channel
 *	Total Size: 1 * 33539 + 4 (header) = 33583 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonio\Desktop\2261\Project\winMusic2.aiff
 *	Time-stamp: Sat Dec 10 14:36:27 2016
 *	
 **************************************************************/

#ifndef __WINMUSIC2H__
#define __WINMUSIC2H__

#define WINMUSIC2FREQ 11025
#define WINMUSIC2LEN 33539

extern const unsigned char winMusic2[33539];

#endif /* __WINMUSIC2H__ */
